### ISSUE TITLE
新的问题

### ISSUE THREAD

**Issue by minercatsc** [biyuhuaping/UISearchControllerDeme#2]
你好，你这个例子非常不错。不过如果把搜索栏放到navbar的titleview中，并且可以自定义大小，能实现你现在的这个效果吗？我一直没有找到方法，可以的话能不能给个思路，谢谢

**Comment by biyuhuaping** [comment]
根据你的描述，想把搜索栏放到导航栏的titleview的中，这个方案可能不太现实，因为当激活搜索时，导航条会上移隐藏，导致无法退出当前页面。苹果给导航条只留了一个口就是：self.navigationItem.searchController，自己无法设置搜索框大小。如果非要实现你想要的效果，可以尝试重写导航条。我也能力有限，哪位大神有更好的办法欢迎留言，共同学习。

**Comment by biyuhuaping** [comment]
突然想到一种办法，就是不用searchController，而是用searchBar这个控件，就能实现你说的效果了。

**Comment by minercatsc** [comment]
谢谢你的解答，非常感谢。用searchBar这个方法你有什么思路吗？

**Comment by asd26187** [comment]
大佬，我在使用你的这个控件的时候遇到了一些问题，不知道能否帮忙解答下。
一个问题就是你的原生demo里搜索栏是在navgationBar下面的，上拉tableView搜索栏会隐藏起来，但是在我这里就是一直显示起来的，我看了几遍源码也没看出是哪一行代码有这个效果。
还有一个问题就是我发现你的searchResultVc里的数据跟前面的控制器数据完全不一样，也就是搜索出来的数据跟前一个界面的数据完全都不一样，这就失去了搜索的意义啊。有可能你只想做一个演示效果，所以全部都写了固定的数据。但是我想知道如何能将前面的一个控制器的数据传给这个searchResultVc呢？传可变数组和不可变数组完全都不可行啊。
望大佬有空给我解答一下，感谢感谢！

**Comment by biyuhuaping** [comment]
@asd26187 第一个问题：模拟器有可能会一直显示，请尽量用真机调试效果。还有一点 iOS 11+，搜索框是放在self.navigationItem.searchController上的，之前是在self.tableView.tableHeaderView上。
第二个问题：因为点击搜框后SearchViewController才被实例化出来，想把dataListArry里的数据传过去需要在UISearchControllerDelegate方法中传过去。
<img width="640" alt="1" src="https://user-images.githubusercontent.com/5062917/39290369-ead66e4a-4961-11e8-867c-610d5b61c88c.png">

根据你的反馈，我把这个demo改了一下，数据变成从上个控制器传过去了。你可以更新看一下。

**Comment by asd26187** [comment]
好的，谢谢大佬，之前我就是发现我在初始化的时候传数据过去不合理，因为首页的数据可能会加载更多。后来实在没办法都准备用数据库传值了，多谢大佬解决我的问题，感谢！
