### ISSUE TITLE
如果在搜索栏搜索字段进入页面，如果能在搜索字段进入的页面隐藏导航栏

### ISSUE THREAD

**Issue by Yulei-Duan** [biyuhuaping/UISearchControllerDeme#3]

**Comment by biyuhuaping** [comment]
这位同学，你的意思是：点击搜索结果，进入下级页面，隐藏导航栏是吗？

**Comment by Yulei-Duan** [comment]
对

**Comment by Yulei-Duan** [comment]
如何能在进入的的下个页面隐藏导航栏，这个我用你的代码试了下，在view willappear 或者 didapear中隐藏，体验并不好，即使能隐藏，动画也是特别不自然。

**Comment by biyuhuaping** [comment]
可以在UISearchControllerDelegate，willPresentSearchController:或willDismissSearchController:中设置
