### ISSUE TITLE
你好，我用你同样的代码继承到项目中，在点击搜索的时候控制器的view 会向下偏移116

### ISSUE THREAD

**Issue by csc-EricWu** [biyuhuaping/UISearchControllerDeme#6]
你好，我用你同样的代码继承到项目中，在点击搜索的时候控制器的view 会向下偏移116

<img width="1258" alt="2018-09-30 22 17 34" src="https://user-images.githubusercontent.com/13517061/46258649-ff60b580-c500-11e8-9038-c6385becdac9.png">

**Comment by csc-EricWu** [comment]
![image](https://user-images.githubusercontent.com/13517061/46258654-42228d80-c501-11e8-8102-3feca9790e42.png)
正常模式没有问题，点击的时候就会跟导航拦之间有间距

**Comment by biyuhuaping** [comment]
@csc-EricWu 你好，我重新实现了，重新试试看还有没有问题。
